parameters:
  service-dir:
    default: "sdk/contentsafety"
emit:
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-python":
    package-dir: "azure-ai-contentsafety"
    package-version: "1.0.0b1"
    package-name: "{package-dir}"
