emit:
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-python":
    package-dir: "openai"
    emitter-output-dir: "{cwd}/{package-dir}"
    package-name: "{package-dir}"
    unbranded: true
